### ISSUE TITLE
Add | Profile Quest 

### ISSUE THREAD

**Issue by YashkShrivas4491** [srajankumar/pullquest#14]
Add: pull quest with a great quote

**Comment by Monika3002** [comment]
"Nothing is impossible because world itself say's I am possible"

**Comment by shubhampr07** [comment]
hello, can you assign this to me

**Comment by srajankumar** [comment]
> hello, can you assign this to me

hello @shubhampr07! 

This issue will be open to everyone and will not specific to anyone, and wont be closed. 

You can add your profile and send the pull request in the repo. I will be accepting the pr's once the clock hits October, as it will be counted towards Hacktoberfest!!

**Comment by ghost** [comment]
Hello I would love to contribute but I am getting an error when i try to push to more forked repo saying

remote: Permission to srajankumar/pullquest.git denied to HondaChan14.
fatal: unable to access 'https://github.com/srajankumar/pullquest.git/': The requested URL returned error: 403

is there permissions on my/your end that I would need to change?

**Comment by srajankumar** [comment]
> Hello I would love to contribute but I am getting an error when i try to push to more forked repo saying
> 
> remote: Permission to srajankumar/pullquest.git denied to HondaChan14. fatal: unable to access 'https://github.com/srajankumar/pullquest.git/': The requested URL returned error: 403
> 
> is there permissions on my/your end that I would need to change?

Hello @HondaChan14 , i think you have cloned directly my repo instead of your forked repo, so you are getting an error while you are pushing the changes.

Use this command to clone your forked repo into your device:

```bash
git clone https://github.com/HondaChan14/pullquest.git
```

**Comment by ghost** [comment]
> > Hello I would love to contribute but I am getting an error when i try to push to more forked repo saying
> > remote: Permission to srajankumar/pullquest.git denied to HondaChan14. fatal: unable to access 'https://github.com/srajankumar/pullquest.git/': The requested URL returned error: 403
> > is there permissions on my/your end that I would need to change?
> 
> Hello @HondaChan14 , i think you have cloned directly my repo instead of your forked repo, so you are getting an error while you are pushing the changes.
> 
> Use this command to clone your forked repo into your device:
> 
> ```shell
> git clone https://github.com/HondaChan14/pullquest.git
> ```

tysm! big face palm I was using the wrong tab haha

**Comment by barkhayadav12** [comment]
Hi @srajankumar my PR have already been merged but in my hactoberfest progress tracker, it isn't showing there. I am new to open source and hactoberfest, can you please explain why it isn't showing there?
