### ISSUE TITLE
Fix Background Wave Image Width Discrepancy for Consistent User Experience

### ISSUE THREAD

**Issue by premsaivarmachekuri** [srajankumar/pullquest#84]
# Description

The background wave image in our project is not occupying the complete width on the right side, while on the left side, it fully extends. This discrepancy results in a white space on the right side of the page, which negatively impacts the user experience. 

# Expected Behavior

The expected behavior is that the background wave image should consistently occupy the full width of the page on both the left and right sides. This would provide a more visually appealing and immersive user experience.

# Screenshot

![image](https://github.com/srajankumar/pullquest/assets/110842297/fef71147-5998-4d35-9035-22a509cf574e)

# Additional Context

Resolving this issue is crucial for enhancing the overall user experience of our project. The inconsistent appearance of the background image can be distracting and affect the visual aesthetics of the page. Achieving a uniform background wave image across the entire width of the page will contribute to a more polished and professional look.

**Comment by khemrajshrestha471** [comment]
Let me solve this issue.  Assign this issue to me.
Thank You!
